config/routes.rb
Rails.application.routes.draw do

  resources :clients
  root "home#index"
  get "/about" => "home#about"

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  resources :posts do
    resources :comments
    resources :favorites, only: [:create, :destroy]
    resources :ratings, only: [:create, :update]
  end
  get "/posts/search" => "posts#search"
  post "/posts/search" => "posts#search", as: :search

  get "/posts/page/:page" => "posts#index", as: :page

  resources :users, only: [:new, :create, :edit, :update]

  get '/changepassword' => 'users#change_password', as: :change_password
  patch '/changepassword' => 'users#update_password'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user, uniqueness: {scope: :post}
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @favorite = Favorite.new
    @post = Post.find params[:post_id]
    @favorite.user = current_user
    @favorite.post = @post

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to post_path(@post) }
        format.js { render '/favorites/write_favorite' }
      else
        format.html { redirect_to post_path(@post) }
        format.js { redirect_to post_path(@post) }
      end
    end
  end

  def destroy
    @favorite = Favorite.find params[:id]
    @post = Post.find params[:post_id]
    @favorite.destroy

    respond_to do |format|
    format.html { redirect_to post_path(@post) }
    format.js { render '/favorites/write_favorite'}

    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<div class="favorite-info">

  <% if @post.favorited_by?(current_user) %>

    <%= link_to "Unfavorite", post_favorite_path(@post, @post.favorite_for(current_user)), method: :delete, remote: true %>

  <% else %>

    <%= link_to "Favorite", post_favorites_path(@post), method: :post, remote: true %>

  <% end %>
</div>

app/views/favorites/write_favorite.js.erb
$('.favorite-info').replaceWith("<%= j( render ( 'favorites/favorite' ) ) %>");