config/routes.rb
Rails.application.routes.draw do

  resources :clients
  root "home#index"
  get "/about" => "home#about"

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  resources :posts do
    resources :comments
    resources :favorites, only: [:create, :destroy]
    resources :ratings, only: [:create, :update]
  end
  get "/posts/search" => "posts#search"
  post "/posts/search" => "posts#search", as: :search

  get "/posts/page/:page" => "posts#index", as: :page

  resources :users, only: [:new, :create, :edit, :update]

  get '/changepassword' => 'users#change_password', as: :change_password
  patch '/changepassword' => 'users#update_password'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
  validates :body, uniqueness: true
  # validates_uniqueness_of :body, scope: :post_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_post, only: [:create, :destroy, :edit, :update]
  before_action :find_comment, only: [:destroy, :edit, :update]
  before_action :authenticate_user!, except: [:show, :index]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new comment_params
    @comment.user = current_user
    @comment.post = @post

    respond_to do |format|
      if @comment.save
        CommentMailer.notify_comment(@comment).deliver_now unless @post.user == current_user
        format.html { redirect_to post_path @post }
        format.js { render 'new_comment' }
      else
        render :new
      end
    end
  end

  def show

  end

  def index
    @comments = Comment.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @comment.update comment_params
      redirect_to post_path @post
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js { render }
    end
  end

  private

    def authenticate_user!
      redirect_to new_session_path, notice: "You have to be signed in" unless user_signed_in?
    end

    def find_post
      @post = Post.find_by_id params[:post_id]
    end

    def find_comment
      @comment = Comment.find params[:id]
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(com) %>">
  <%= com.user.full_name + " says:" if com.user %><br>
  <%= com.body %>
  <% if (can? :manage, com) || (can? :manage, @post) %>
    <%= link_to "Edit", edit_post_comment_path( @post, com ) %>
    <%= link_to "Delete",post_comment_path( @post, com ), remote: true, method: :delete %>
  <% end %>
  <hr>
</div>

app/views/comments/_form.html.erb
<h3>Leave a Comment</h3>
<%= form_for [@post, @comment], remote: true do |f| %>
  <%= f.text_area :body %>
  <%= f.submit "Post Comment" %>
<% end %>

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(1000, function(){
  $(this).remove();
})

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render "shared/comment_form" %>

app/views/comments/index.html.erb
<h1>All Comments</h1>
<%= link_to "New Comment", new_comment_path %>
<%= @comments.each do |comment| %>
  <p><%= link_to "Edit Comment", comment_path(comment) %></p>
  <%= comment.body %>
  <hr>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render "shared/comment_form" %>

app/views/comments/new_comment.js.erb
$('#comments').prepend("<%= j render( '/comments/comment', { com: @comment } ) %>");

<% @comment = Comment.new %>

$('#comment-form').html("<%= j render( '/comments/form' )%>");

app/views/comments/show.html.erb
<h1>Comment</h1>
<%= @comment.body %>
<%= link_to "Edit", edit_comment_path(@comment) %>
<%= link_to "Delete",comment_path(@comment), method: :delete,
                                            data: {confirm: "Are you sure you want to delete this comment"} %>