config/routes.rb
Rails.application.routes.draw do

  resources :clients
  root "home#index"
  get "/about" => "home#about"

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  resources :posts do
    resources :comments
    resources :favorites, only: [:create, :destroy]
    resources :ratings, only: [:create, :update]
  end
  get "/posts/search" => "posts#search"
  post "/posts/search" => "posts#search", as: :search

  get "/posts/page/:page" => "posts#index", as: :page

  resources :users, only: [:new, :create, :edit, :update]

  get '/changepassword' => 'users#change_password', as: :change_password
  patch '/changepassword' => 'users#update_password'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #


      user ||= User.new # guest user (not logged in)

      can :manage, [Post, Comment] do |p|
        p.user == user
      end



      if user.is_admin?
        can :manage, :all
      else
        can :read, :all
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
  validates :body, uniqueness: true
  # validates_uniqueness_of :body, scope: :post_id
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user, uniqueness: {scope: :post}
end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessor :post_on_twitter
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :ratings, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  validates :title, presence: true,
                    uniqueness: true

  validates :body, presence: true,
                   length: { minimum: 7 }

  scope :most_recent, -> {order(created_at: :desc).limit(6)}

  scope :search, -> (term) { where("body ILIKE :term OR title ILIKE :term", {term: "%#{ term }%"})}

  def self.paginate(current_page)
    per_page_count = 12
    page_num = current_page.to_i
    order(created_at: :desc).offset(per_page_count * (page_num - 1)).limit(per_page_count)
  end

  def body_snippet
    body.truncate(100)
  end

  def favorited_by?(user)
    favorites.exists?(user: user)
  end

  def favorite_for(user)
    favorites.find_by_user_id user
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_inclusion_of :rating, in: 1..5
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :posts


  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    unless: :using_oauth?
  validates :uid, uniqueness: {scope: :provider}, if: :using_oauth?

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.create_from_twitter(twitter_data)
    user = User.new
    full_name = twitter_data["info"]["name"].split(" ")
    user.first_name = full_name.first
    user.last_name = full_name.last
    user.uid = twitter_data["uid"]
    user.provider = twitter_data["provider"]
    user.twitter_token = twitter_data["credentials"]["token"]
    user.twitter_secret = twitter_data["credentials"]["secret"]
    user.twitter_raw_data = twitter_data
    user.password = SecureRandom.urlsafe_base64
    user.save!
    user
  end

  def self.find_or_create_from_twitter(twitter_data)
    user = User.where(uid: twitter_data["uid"], provider: twitter_data["provider"]).first
    user = create_from_twitter(twitter_data) unless (user)
    user
  end

  def using_oauth?
    uid.present? && provider.present?
  end

  PROVIDER_TWITTER = "twitter"
  def using_twitter?
    using_oauth? && provider == PROVIDER_TWITTER
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.most_recent
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
  <div class="flash-notice"><%= flash[:notice] %></div>
<% elsif flash[:alert] %>
  <div class="flash-alert"><%= flash[:alert] %></div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="nav-bar">
  <%= link_to "Home", root_path %> |
  <%= link_to "About", about_path %> |
  <%= link_to "All Posts", posts_path %> |
  <% if user_signed_in? %>
    Signed in as: <%= link_to current_user.first_name, edit_user_path(current_user) %> |
    <%= link_to "Sign out", sessions_path, method: :delete %>
  <% else %>
    <%= link_to "Create an Account", new_user_path %> |
    <%= link_to "Sign In", new_session_path %>
  <% end %>
</nav>

app/views/layouts/_search_bar.html.erb
<div class="search">
  <%= form_tag search_path do %>
    <%= text_field_tag :search %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
<%= render "/layouts/nav_bar" %>
<div class="container">
  <%= render "/layouts/search_bar" %>
  <%= render "/layouts/flash_messages" %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/shared/_display_comment.html.erb
<%= @comment.body %>
<%= link_to "Edit", edit_comment_path(@comment) %>
<%= link_to "Delete",comment_path(@comment), method: :delete,
                                            data: {confirm: "Are you sure you want to delete this comment"} %>

app/views/shared/_display_post.html.erb
<a href="<%= post_path(post) %>" class="post-link">
<div class="col s12 m6 l4">
  <div class="post">
    <h2 class="post-title"><%= post.title %></h2>
    <div class="post-body">
      <%= post.body.truncate(100) %>
    </div>
  </div>
</div>
</a>

app/views/shared/_post_form.html.erb
<%= form_for @post do |f|%>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.label :tags %>
    <%= f.collection_check_boxes(:tag_ids, Tag.order(:title), :id, :title) %>
  </div>
  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :title %>
  </div>
  <% if current_user.using_twitter? %>
  <div>
    <%= f.check_box :post_on_twitter, as: :boolean %>
    <%= f.label :post_on_twitter %>
  </div>
  <% end %>
  <%= f.submit %>
<% end %>